/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/* 
 * File:   Constants.cpp
 * Author: petrstepanov
 * 
 * Created on August 19, 2017, 11:30 PM
 */

#include "Constants.h"
#include <TMath.h>

const char* Constants::applicationName = "SW Calculator";

const Double_t Constants::padMargin[4] = {0.10, 0.03, 0.15, 0.05}; // left, right, bottom, top
const Int_t Constants::colorSet[7]  = {kViolet+6, kSpring-5, kAzure+8, kPink+1, kGray+1, kViolet-4, kRed-7};

TColor* Constants::colorPrimary   = new TColor(0.232, 0.757, 0.832);
TColor* Constants::colorWarning   = new TColor(0.832, 0.769, 0.232);
TColor* Constants::colorGray      = new TColor(0.5, 0.5, 0.5);
TColor* Constants::colorAppWindow = new TColor(0.906, 0.906, 0.906);

RooConstVar* Constants::fwhm2sigma = new RooConstVar("fwhm2sigma", "Coefficient to convert FWHM to dispersion", 1/TMath::Sqrt(8*TMath::Log(2)));
RooConstVar* Constants::pi = new RooConstVar("pi", "pi", TMath::Pi());

char* Constants::applicationIcon[] = {
		"64 64 109 2",
		"  	c None",
		". 	c #FFFFFF",
		"+ 	c #A9E3F5",
		"@ 	c #81D9F2",
		"# 	c #84D9F2",
		"$ 	c #CFF0FA",
		"% 	c #65CEEE",
		"& 	c #00AEE3",
		"* 	c #00B6E6",
		"= 	c #00B8E6",
		"- 	c #00B1E4",
		"; 	c #36C0E9",
		"> 	c #F5FCFE",
		", 	c #FEFFFF",
		"' 	c #E5F6FC",
		") 	c #0FB4E5",
		"! 	c #00B9E6",
		"~ 	c #00B7E6",
		"{ 	c #01B8E6",
		"] 	c #0AB3E5",
		"^ 	c #EDF9FD",
		"/ 	c #DFF5FB",
		"( 	c #00B2E5",
		"_ 	c #15B6E5",
		": 	c #EFFAFD",
		"< 	c #03B4E5",
		"[ 	c #49C7EC",
		"} 	c #19B7E6",
		"| 	c #00B3E4",
		"1 	c #B5E8F7",
		"2 	c #43C5EB",
		"3 	c #06B3E5",
		"4 	c #92DDF3",
		"5 	c #00B4E5",
		"6 	c #78D5F0",
		"7 	c #D1F1FA",
		"8 	c #00B0E4",
		"9 	c #00AFE3",
		"0 	c #F7FEFF",
		"a 	c #F4FCFE",
		"b 	c #00B8E7",
		"c 	c #5FCEEE",
		"d 	c #21BAE7",
		"e 	c #F1FBFE",
		"f 	c #39C1EA",
		"g 	c #5BCCEE",
		"h 	c #59D8F9",
		"i 	c #00B5E5",
		"j 	c #F0FBFE",
		"k 	c #61DFFF",
		"l 	c #28CFFA",
		"m 	c #00B6E5",
		"n 	c #4CDBFF",
		"o 	c #34D6FF",
		"p 	c #2AD0FA",
		"q 	c #EFFBFD",
		"r 	c #E2F9FF",
		"s 	c #31D6FF",
		"t 	c #38D7FF",
		"u 	c #5ACCEE",
		"v 	c #88E7FF",
		"w 	c #21D2FF",
		"x 	c #35D6FF",
		"y 	c #ECFAFD",
		"z 	c #A3ECFF",
		"A 	c #2CD4FF",
		"B 	c #36D6FF",
		"C 	c #52C9EC",
		"D 	c #D9F7FF",
		"E 	c #7FE5FF",
		"F 	c #25D3FF",
		"G 	c #33D6FF",
		"H 	c #00B0E3",
		"I 	c #DFF6FD",
		"J 	c #FDFFFF",
		"K 	c #E7FAFF",
		"L 	c #BBF1FF",
		"M 	c #94E9FF",
		"N 	c #67E0FF",
		"O 	c #29D4FF",
		"P 	c #24D3FF",
		"Q 	c #4CD7FA",
		"R 	c #1FD1FF",
		"S 	c #1DD1FF",
		"T 	c #1AD1FF",
		"U 	c #20D2FF",
		"V 	c #30D5FF",
		"W 	c #1ECDFA",
		"X 	c #C3F3FF",
		"Y 	c #8DE8FF",
		"Z 	c #E9FBFF",
		"` 	c #3FD8FF",
		" .	c #7EE5FF",
		"..	c #C4F3FF",
		"+.	c #DFF9FF",
		"@.	c #2BD4FF",
		"#.	c #E0F9FF",
		"$.	c #B9F1FF",
		"%.	c #28D4FF",
		"&.	c #66E0FF",
		"*.	c #87E7FF",
		"=.	c #37D7FF",
		"-.	c #1CD1FF",
		";.	c #59DDFF",
		">.	c #97EAFF",
		",.	c #CDF5FF",
		"'.	c #F3FDFF",
		").	c #2AD4FF",
		"!.	c #1BD1FF",
		". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ",
		". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ",
		". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ",
		". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ",
		". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ",
		". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ",
		". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ",
		". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ",
		". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ",
		". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ",
		". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ",
		". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ",
		". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . + @ # $ . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ",
		". . . . . . . . . . . . . . . . . . . . . . . . . . . . % & * = = - ; > , . . . . . . . . . . . . . . . . . . . . . . . . . . . ",
		". . . . . . . . . . . . . . . . . . . . . . . . . , ' ) ! ~ ~ ~ ~ ~ { ] ^ . . . . . . . . . . . . . . . . . . . . . . . . . . . ",
		". . . . . . . . . . . . . . . . . . . . . . . . , / ( ~ ~ ~ ~ ~ ~ ~ ~ = _ . . . . . . . . . . . . . . . . . . . . . . . . . . . ",
		". . . . . . . . . . . . . . . . . . . . . . . . : < ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ { [ . . . . . . . . . . . . . . . . . . . . . . . . . . ",
		". . . . . . . . . . . . . . . . . . . . . . . . } = ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ | 1 , . . . . . . . . . . . . . . . . . . . . . . . . ",
		". . . . . . . . . . . . . . . . . . . . . . . 2 ! ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ 3 . . . . . . . . . . . . . . . . . . . . . . . . . ",
		". . . . . . . . . . . . . . . . . . . . . . 4 5 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ = 6 . . . . . . . . . . . . . . . . . . . . . . . . ",
		". . . . . . . . . . . . . . . . . . . . , 7 8 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ 9 0 . . . . . . . . . . . . . . . . . . . . . . . ",
		". . . . . . . . . . . . . . . . . . . . a < ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ b c . . . . . . . . . . . . . . . . . . . . . . . ",
		". . . . . . . . . . . . . . . . . . . . d { ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ 9 e . . . . . . . . . . . . . . . . . . . . . . ",
		". . . . . . . . . . . . . . . . . . . f = ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ { g . . . . . . . . . . . . . . . . . . . . . . ",
		". . . . . . . . . . . . . . . . . . h i ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ 9 j . . . . . . . . . . . . . . . . . . . . . ",
		". . . . . . . . . . . . . . . . . k l m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ = g . . . . . . . . . . . . . . . . . . . . . ",
		". . . . . . . . . . . . . . . . n o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ 9 q . . . . . . . . . . . . . . . . . . . . ",
		". . . . . . . . . . . . . . r s t o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ = u . . . . . . . . . . . . . . . . . . . . ",
		". . . . . . . . . . . . . v w x o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ 9 y . . . . . . . . . . . . . . . . . . . ",
		". . . . . . . . . . . z A B o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ = C . . . . . . . . . . . . . . . . . . . ",
		". . . . . . . . D E F G o o o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ H I . . . . . . . . . . . . . . . . . . ",
		". . J K L M N O P B o o o o o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ m Q . . . . . . . . . . . . . . . . . . ",
		"R S T U V B x o o o o o o o o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ m W X . . . . . . . . . . . . . . . . . ",
		"o o o o o o o o o o o o o o o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ m p s . . . . . . . . . . . . . . . . . ",
		"o o o o o o o o o o o o o o o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ m p x Y . . . . . . . . . . . . . . . . ",
		"o o o o o o o o o o o o o o o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ m p o U Z . . . . . . . . . . . . . . . ",
		"o o o o o o o o o o o o o o o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ m p o x ` . . . . . . . . . . . . . . . ",
		"o o o o o o o o o o o o o o o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ m p o o x  .. . . . . . . . . . . . . . ",
		"o o o o o o o o o o o o o o o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ m p o o o P .., . . . . . . . . . . . . ",
		"o o o o o o o o o o o o o o o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ m p o o o o F +., . . . . . . . . . . . ",
		"o o o o o o o o o o o o o o o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ m p o o o o o @.K , . . . . . . . . . . ",
		"o o o o o o o o o o o o o o o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ m p o o o o o x @.#.. . . . . . . . . . ",
		"o o o o o o o o o o o o o o o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ m p o o o o o o o F $.. . . . . . . . . ",
		"o o o o o o o o o o o o o o o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ m p o o o o o o o o %.&.. . . . . . . . ",
		"o o o o o o o o o o o o o o o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ m p o o o o o o o o o t w *.. . . . . . ",
		"o o o o o o o o o o o o o o o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ m p o o o o o o o o o o o =.-.;.>.,.'.. ",
		"o o o o o o o o o o o o o o o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ m p o o o o o o o o o o o o o x x ).!.!.",
		"o o o o o o o o o o o o o o o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ m p o o o o o o o o o o o o o o o o o o ",
		"o o o o o o o o o o o o o o o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ m p o o o o o o o o o o o o o o o o o o ",
		"o o o o o o o o o o o o o o o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ m p o o o o o o o o o o o o o o o o o o ",
		"o o o o o o o o o o o o o o o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ m p o o o o o o o o o o o o o o o o o o ",
		"o o o o o o o o o o o o o o o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ m p o o o o o o o o o o o o o o o o o o ",
		"o o o o o o o o o o o o o o o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ m p o o o o o o o o o o o o o o o o o o ",
		"o o o o o o o o o o o o o o o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ m p o o o o o o o o o o o o o o o o o o ",
		"o o o o o o o o o o o o o o o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ m p o o o o o o o o o o o o o o o o o o ",
		"o o o o o o o o o o o o o o o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ m p o o o o o o o o o o o o o o o o o o ",
		"o o o o o o o o o o o o o o o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ m p o o o o o o o o o o o o o o o o o o ",
		"o o o o o o o o o o o o o o o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ m p o o o o o o o o o o o o o o o o o o ",
		"o o o o o o o o o o o o o o o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ m p o o o o o o o o o o o o o o o o o o ",
		"o o o o o o o o o o o o o o o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ m p o o o o o o o o o o o o o o o o o o ",
		"o o o o o o o o o o o o o o o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ m p o o o o o o o o o o o o o o o o o o ",
		"o o o o o o o o o o o o o o o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ m p o o o o o o o o o o o o o o o o o o ",
		"o o o o o o o o o o o o o o o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ m p o o o o o o o o o o o o o o o o o o ",
		"o o o o o o o o o o o o o o o o o o p m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ m p o o o o o o o o o o o o o o o o o o "};
